curabox/force-app/main/default/objects/Follow_up_Task__c/Follow_up_Task__c.object-meta.xml
<CustomObject>
<!--     <gender>Feminine</gender> -->
    <label>Follow-up Task</label>
    <nameField>
        <displayFormat>FT-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow-up Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

curabox/force-app/main/default/objects/Follow_up_Task__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Follow-up Tasks</relationshipLabel>
    <relationshipName>Follow_up_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

curabox/force-app/main/default/objects/Follow_up_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Fälligkeitsdatum</label>
    <type>DateTime</type>
</CustomField>

curabox/force-app/main/default/objects/Follow_up_Task__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Thema</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lieferung angehalten</fullName>
            </value>
            <value>
                <fullName>Antrag unvollständig</fullName>
            </value>
            <value>
                <fullName>Kündigung einstellen</fullName>
            </value>
            <value>
                <fullName>Rückruf</fullName>
            </value>
            <value>
                <fullName>Bedarfsmeldung</fullName>
            </value>
            <value>
                <fullName>Klaerung AOK Rheinland/HH</fullName>
            </value>
            <value>
                <fullName>Nachfassen bei PK wg. offener KÜ</fullName>
            </value>
            <value>
                <fullName>Adressänderung einstellen</fullName>
            </value>
            <value>
                <fullName>Storno</fullName>
            </value>
            <value>
                <fullName>Storno - Rückruf</fullName>
            </value>
            <value>
                <fullName>Storno- Rückmeldung</fullName>
            </value>
            <value>
                <fullName>Wohin soll cb geliefert werden?</fullName>
            </value>
            <value>
                <fullName>Ablehnung</fullName>
            </value>
            <value>
                <fullName>PG51 genehmigt</fullName>
            </value>
            <value>
                <fullName>Sonstiges</fullName>
            </value>
            <value>
                <fullName>Nachlieferung</fullName>
            </value>
            <value>
                <fullName>Genehmigung PG54 läuft aus</fullName>
            </value>
            <value>
                <fullName>Genehmigung PG51 läuft aus</fullName>
            </value>
            <value>
                <fullName>DPD Rückläufer</fullName>
            </value>
            <value>
                <fullName>DPD- Zustellhindernisse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

curabox/force-app/main/default/classes/FlowController_Test.cls
@isTest
public class FlowController_Test{
	

	static testMethod void test_FollowUpTasksController(){
		//create contact
		Contact contact = new Contact(Lastname = 'test', Email = 'test@email.com');
		insert contact;
		//create follow up task 
		List<Follow_up_Task__c> tasks = new List<Follow_up_Task__c>();
		Follow_up_Task__c followUpTask = new Follow_up_Task__c(Subject__c = 'Lieferung angehalten', Due_Date__c = System.now(), contact__c = contact.Id);
		insert followUpTask;
		tasks.add(followUpTask);
		//instanciate  FlowController class
		FlowController flowController = new FlowController();
        flowController.followUpTasksToUpdate=tasks;
		//edit  a followUpTask in followUpTasksToUpdate
		flowController.followUpTasksToUpdate[0].Due_Date__c = System.now()+1;
        //check UpdatedFollowUpTasks
		System.assertEquals(flowController.UpdatedFollowUpTasks == null, false);
   
      	//assign contactId
        flowController.contactId=contact.Id;
        //check contact
		System.assertEquals(flowController.Contact == null, false);
	}
    
 
}