curabox/force-app/main/default/objects/Contact/fields/Salutation_Text_Curabox__c.field-meta.xml
<CustomField>
    <fullName>Salutation_Text_Curabox__c</fullName>
    <formula>if ( ISPICKVAL( Salutation , &apos;Herr&apos;),
&apos;Lieber Herr &apos;,
if ( ISPICKVAL( Salutation , &apos;Frau&apos;),
&apos;Liebe Frau &apos;,
&apos;Sehr geehrte Damen und Herren&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Anrede Text Curabox</label>
    <type>Text</type>
</CustomField>

curabox/force-app/main/default/objects/Contact/fields/Status_PG51__c.field-meta.xml
<CustomField>
    <fullName>Status_PG51__c</fullName>
    <label>Status PG51</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Interessent</fullName>
            </value>
            <value>
                <fullName>Kandidat</fullName>
            </value>
            <value>
                <fullName>Kunde</fullName>
            </value>
            <value>
                <fullName>Kündigung</fullName>
            </value>
            <value>
                <fullName>Vorgang geschlossen</fullName>
            </value>
            <value>
                <fullName>Formular unerwünscht</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

curabox/force-app/main/default/objects/Contact/fields/Status_PG54__c.field-meta.xml
<CustomField>
    <fullName>Status_PG54__c</fullName>
    <label>Status PG54</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Interessent</fullName>
            </value>
            <value>
                <fullName>Kandidat</fullName>
            </value>
            <value>
                <fullName>Kunde</fullName>
            </value>
            <value>
                <fullName>Kündigung</fullName>
            </value>
            <value>
                <fullName>Vorgang geschlossen</fullName>
            </value>
            <value>
                <fullName>Formular unerwünscht</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

curabox/force-app/main/default/objects/Contact/fields/WorkAroundTemplatesAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>WorkAroundTemplatesAccountNumber__c</fullName>
    <formula>Account.Familien_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WorkAroundTemplatesAccountNumber</label>
    <type>Text</type>
</CustomField>

curabox/force-app/main/default/objects/Follow_up_Task__c/Follow_up_Task__c.object-meta.xml
<CustomObject>
<!--     <gender>Feminine</gender> -->
    <label>Follow-up Task</label>
    <nameField>
        <displayFormat>FT-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow-up Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

curabox/force-app/main/default/objects/Follow_up_Task__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Follow-up Tasks</relationshipLabel>
    <relationshipName>Follow_up_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

curabox/force-app/main/default/objects/Follow_up_Task__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Thema</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lieferung angehalten</fullName>
            </value>
            <value>
                <fullName>Antrag unvollständig</fullName>
            </value>
            <value>
                <fullName>Kündigung einstellen</fullName>
            </value>
            <value>
                <fullName>Rückruf</fullName>
            </value>
            <value>
                <fullName>Bedarfsmeldung</fullName>
            </value>
            <value>
                <fullName>Klaerung AOK Rheinland/HH</fullName>
            </value>
            <value>
                <fullName>Nachfassen bei PK wg. offener KÜ</fullName>
            </value>
            <value>
                <fullName>Adressänderung einstellen</fullName>
            </value>
            <value>
                <fullName>Storno</fullName>
            </value>
            <value>
                <fullName>Storno - Rückruf</fullName>
            </value>
            <value>
                <fullName>Storno- Rückmeldung</fullName>
            </value>
            <value>
                <fullName>Wohin soll cb geliefert werden?</fullName>
            </value>
            <value>
                <fullName>Ablehnung</fullName>
            </value>
            <value>
                <fullName>PG51 genehmigt</fullName>
            </value>
            <value>
                <fullName>Sonstiges</fullName>
            </value>
            <value>
                <fullName>Nachlieferung</fullName>
            </value>
            <value>
                <fullName>Genehmigung PG54 läuft aus</fullName>
            </value>
            <value>
                <fullName>Genehmigung PG51 läuft aus</fullName>
            </value>
            <value>
                <fullName>DPD Rückläufer</fullName>
            </value>
            <value>
                <fullName>DPD- Zustellhindernisse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

curabox/force-app/main/default/classes/FlowController.cls
/**
 * @CloudMonsters
 * Last Changed 18.05.2021
 * Flow Controller
 *@description :class used by visual flows
 **/
public class FlowController{
    
	/**************** map contact***************************/
	public Map<Id, Contact> contactsMap{
		get{
			if (contactsMap == null){
                
             Set<Id> contactIds = new Set<Id>();
				if (UpdatedFollowUpTasks != null){
					for (Follow_up_Task__c task : UpdatedFollowUpTasks){
					contactIds.add(task.Contact__c);
					}
				}
                
			  contactsMap = new Map<Id, Contact>([SELECT Id,Status_PG54__c,Status_PG51__c , LastName, Name, Salutation, Salutation_Text_Curabox__c, WorkAroundTemplatesAccountNumber__c, Email
				                                    FROM Contact
				                                    WHERE Email != null AND Id =:contactIds ]);
			}
			return contactsMap;
		}
		set;
	}

	/*Input */
	@AuraEnabled
	public Id contactId;

	/*Output */
	/*Get Contact Record by Id*/
	@AuraEnabled
	public Contact Contact{
		get{
			return contactsMap.get(contactId);
		}
		set;
	}

	/**************** get successfully updated  FollowUpTasks ***************************/
	/*Input */
	@AuraEnabled
	public List<Follow_up_Task__c> followUpTasksToUpdate;
	/*Output */
	@AuraEnabled
	public List<Follow_up_Task__c> UpdatedFollowUpTasks{
		get{
			Set<Id> updatedFollowUpTasksIds = new Set<Id>();
			if (followUpTasksToUpdate != null){
				//get successfully updated records
				Database.saveResult[] srList = Database.update(followUpTasksToUpdate, false);
				for (Database.SaveResult sr : srList){
					if (sr.isSuccess()){
						updatedFollowUpTasksIds.add(sr.getId());
					}
				}
			}
			return [SELECT Id, Contact__c, Subject__c
			        FROM Follow_up_Task__c
			        where Id in :updatedFollowUpTasksIds];
		}

		set;
	}
}